### ISSUE TITLE
Criar o diagrama de entidade relacionamento (DER)

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#1]
Fazer o DER no banco de dados MySQL.

Pensar nos dados que serão necessários

**Comment by MaykoDiouzef** [comment]
bd adicionado.

**Comment by Ronneesley** [comment]
Mudar nomenclatura das tabelas para o plural: ex. curso -> cursos.
Mudar a nomenclatura dos IDs para apenas: id. Ex.:
idcurso -> id, idquestao -> id
Mudar a nomenclatura das chaves estrangeiras. Ex.:
fkidcurso -> curso, fkidquestao -> questao
Unir: pergunta, questao e resposta.
Ajustar o texto do campo: respostaerra1 -> respostaerrada1.
Mudar nome da tabela hanking para ranks
Mudar nome da tabela nomequiz -> quizzes
Mudar nome da tabela quiz -> perguntas_quiz
Retirar o campo acesso da tabela administrador
Senha do administrador para 32 caracteres.
Verificar tamanho das respostas erradas text.

**Comment by MaykoDiouzef** [comment]
- [x] Mudar nomenclatura das tabelas para o plural: ex. curso -> cursos.
- [x]  Mudar a nomenclatura dos IDs para apenas: id. Ex.: idcurso -> id, idquestao -> id
- [x] Mudar a nomenclatura das chaves estrangeiras. Ex.: fkidcurso -> curso, fkidquestao -> questao
- [x] Unir: pergunta, questao e resposta.
- [x] Ajustar o texto do campo: respostaerra1 -> respostaerrada1.
- [x] Mudar nome da tabela hanking para ranks
- [x] Mudar nome da tabela nomequiz -> quizzes
- [x] Mudar nome da tabela quiz -> perguntas_quiz
- [x] Retirar o campo acesso da tabela administrador
- [x] Senha do administrador para 32 caracteres.
- [x] Verificar tamanho das respostas erradas text.

Foram realizadas todas as alterações.

**Comment by Ronneesley** [comment]
- [ ] Em perguntas_quiz, mudar quizzes -> quiz
- [ ] Em perguntas, mudar imagem para o tipo de dado blob

**Comment by Ronneesley** [comment]
Feito
