### ISSUE TITLE
Criar página HTML dos conceitos estatísticos: pesquisa, amostragem, conjuntos, etc.

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#11]
● Pesquisa estatística.
● Amostragem (tipos de amostragem).
● Conjuntos e subconjuntos (finito e infinito).
● Dado x Variável.

**Comment by Uigorteodoro** [comment]
Atividade Feita

**Comment by Ronneesley** [comment]
Feito
