### ISSUE TITLE
Fazer o cadastro de administradores

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#121]
Os dados dos administradores são: id, nome, email, senha

**Comment by Emanuel331** [comment]
Salvo como cadastro_admin.html

**Comment by Ronneesley** [comment]
Arquivo movido para `templates/admin/administradores/cadastro.html` seguir os modelos.
Colocar rótulos nos campos.

**Comment by Ronneesley** [comment]
Issue correlata adicionada: #128

**Comment by Emanuel331** [comment]
Alterado

**Comment by Ronneesley** [comment]
Vi aqui que colocou os rótulos, favor só colocar o ID como sendo o primeiro campo. 
Já vou considerar fechada a tarefa, mas aguardo o envio desta modificação.

Feito.
