### ISSUE TITLE
Fazer o HTML da tela de ranks

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#122]
Fazer o HTML da tela de Ranks conforme o protótipo **Prototipo Completo.png**

**Comment by Emanuel331** [comment]
Salvo como ranks1.html, ranks2.html, ranks3.html, ranks4.html

**Comment by Ronneesley** [comment]
Somente o arquivo `ranks4.html` era necessário. Movido para a pasta `admin/rank/rank.html`. Feito.
