### ISSUE TITLE
Criar HTML da tela de perguntas: Quiz

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#25]
Fazer o HTML da tela de perguntas. Fixem uma pergunta como exemplo e coloquem as quatro opções.

Simulem um exemplo de resposta errada. Colocando a explicação do porque a resposta certa está correta, contendo um link para a página de conteúdo relacionado ao assunto. Ex.:

Qual a média de: 1, 4, 5, 8?

Mostrar a resposta correta. Simulando que o usuário errou. E a explicação que apareceria tentando ajudá-lo no aprendizado.

**Comment by Ronneesley** [comment]
Ver arquivo do protótipo

**Comment by joaofellip33** [comment]
Boa tarde!
Não conseguir contar a equipe, mas fica aqui o aviso de que já iniciei a página html desta atividade, falta alguns detalhes e o projeto já esta no git. 
Qualquer dúvida podem me chamar no whatsapp (62) 98132-7706

**Comment by Ronneesley** [comment]
@lyzlopes, o grupo já estava fechado

**Comment by Ronneesley** [comment]
Feito
