### ISSUE TITLE
Planejar o que será calculado a nível estatístico

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/quizestatistico#6]
Fazer um documento mostrando o que será realizado dentro do sistema e quais funções estatísticas serão utilizadas.

**Comment by Ronneesley** [comment]
Permissão para entrada Ana Clara no grupo

**Comment by anaclaralacerda9** [comment]
Arquivo enviado.

**Comment by Ronneesley** [comment]
Após organização dos grupos, ficaram estas pessoas e a tarefa foi enviada.
